version: '3.4'

services:

  server:
    build:
      context: server
    working_dir: /src
    ports:
    - 9090:9090
    restart: always
    command: ["python", "main.py"]
    environment:
      - DINNER_STORAGE_DIR=/storage
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=9090
      - RECIPES_DIR=/storage
    volumes:
    - ./storage/:/storage
    - ./server/src:/src

  envoy:
    build:
      context: envoy
    ports:
      - "8080:8080"
    links:
      - server

# Don't actually use this right now but keep it around just in case
#  db:
#    build:
#      context: database
#    volumes:
#      - ./storage/postgres_data:/var/lib/postgresql/data/

  protobufs:
    build:
      context: protobufs
    volumes:
      - ./protobufs/recipe.proto:/recipe.proto
      - ./frontend/src/messages:/build/typescript
      - ./server/src/proto:/build/python

  frontend:
    build:
      context: frontend
    volumes:
      - ./frontend:/app
    ports:
      - 3001:3000