version: '3.9'

services:
  server:
    image: evamicur/dinner-server:${DINNER_TAG}
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 9090:9090
    volumes:
      - ./server/data:/server/data
    # depends_on:
    #   - db
    environment:
      - RUST_LOG=info
      - DINNER_HOST=0.0.0.0:9090
#      Oh apparently you use the container local port within the same service not the outside one
      - "DATABASE_URL=postgres://postgres:abc123@db:5432/dinner"

  envoy:
    image: evamicur/dinner-envoy:${DINNER_TAG}
    build:
      context: envoy
    ports:
      - "8080:8080"
      - "9901:9901"
    links:
      - server

  db:
    image: evamicur/dinner_db:${DINNER_TAG}
    build:
      context: database
    volumes:
      - ./storage/postgres_data:/var/lib/postgresql/data/
    ports:
      - 8002:5432

  protobufs:
    build:
      context: protobufs
    volumes:
      - ./protobufs/recipe.proto:/recipe.proto
      - ./frontend/src/messages:/build/typescript

  frontend:
    depends_on:
      - envoy
      - server

    image: evamicur/dinner-frontend:${DINNER_TAG}
    build:
      context: frontend
      target: prod
    ports:
      - 80:80

  frontend-dev:
    image: evamicur/frontend-dev:${DINNER_TAG}
    depends_on:
      - envoy
      - server
    build:
      context: frontend
      target: dev
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3001:3000