version: '3.4'

services:

  server:
    build:
      context: server
    ports:
    - 8000:8000
    restart: always
    volumes:
    - ./server/:/site
    environment:
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=hello_django_dev
      - SQL_USER=hello_django
      - SQL_PASSWORD=hello_django
      - SQL_HOST=db
      - SQL_PORT=5432
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1] 0.0.0.0
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    depends_on:
      - db

  db:
    build:
      context: database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev


  protobufs:
    build:
      context: protobufs
    volumes:
      - ./frontend/src:/build/elm
      - ./server/proto:/build/python
volumes:
  postgres_data: