# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: recipe.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Recipe(betterproto.Message):
    name: str = betterproto.string_field(1)
    id: int = betterproto.int32_field(2)
    email: str = betterproto.string_field(3)
