name: Publish release
on:
  release:
    published:

env:
  DINNER_TAG: test

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: test
        run: echo ${{ secrets.TEST_SECRET }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build
        run: docker-compose build

      - name: push
        run: docker-compose push
