name: Build
on:
  pull_request:

env:
  DINNER_TAG: test

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build
        run: docker-compose build
